import RepaymentList from "@/forms/RepaymentList";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "لیست تسهیلات",
  description: "Generated by morteza kia",
};

export default function page() {
  return <RepaymentList />;
}
